In [5]:
import pandas as pd
from sqlalchemy import create_engine, URL, text
import os
from dotenv import load_dotenv
print(os.getcwd())
load_dotenv("../.env")
database_url = URL.create(
    drivername="postgresql+psycopg",
    username=os.getenv("POSTGRES_USER"),
    password=os.getenv("POSTGRES_PASSWORD"),
    host=os.getenv("POSTGRES_HOST", "localhost"),
    port=int(os.getenv("POSTGRES_PORT", 5432)),
    database=os.getenv("POSTGRES_DB"),
)

engine = create_engine(database_url)

c:\Users\kakas\Desktop\projects\Brazilian E-Commerce Public Dataset by Olist\notebooks

In [8]:
customers = pd.read_csv('../data/olist_customers_dataset.csv')
geolocation = pd.read_csv('../data/olist_geolocation_dataset.csv')
order_items = pd.read_csv('../data/olist_order_items_dataset.csv')
order_payments = pd.read_csv('../data/olist_order_payments_dataset.csv')
order_reviews = pd.read_csv('../data/olist_order_reviews_dataset.csv')
orders = pd.read_csv('../data/olist_orders_dataset.csv')
products = pd.read_csv('../data/olist_products_dataset.csv')
sellers = pd.read_csv('../data/olist_sellers_dataset.csv')
category_translation = pd.read_csv('../data/product_category_name_translation.csv')

In [9]:
customers.to_sql(
    "customers",
    engine,
    if_exists="replace",
    index=False
)

geolocation.to_sql(
    "geolocation",
    engine,
    if_exists="replace",
    index=False
)

order_items.to_sql(
    "order_items",
    engine,
    if_exists="replace",
    index=False
)

order_payments.to_sql(
    "order_payments",
    engine,
    if_exists="replace",
    index=False
)

order_reviews.to_sql(
    "order_reviews",
    engine,
    if_exists="replace",
    index=False
)

orders.to_sql(
    "orders",
    engine,
    if_exists="replace",
    index=False
)

products.to_sql(
    "products",
    engine,
    if_exists="replace",
    index=False
)

sellers.to_sql(
    "sellers",
    engine,
    if_exists="replace",
    index=False
)

category_translation.to_sql(
    "category_translation",
    engine,
    if_exists="replace",
    index=False
)

-1

In [10]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';
"""

pd.read_sql(query, engine)

             table_name
0             customers
1           geolocation
2           order_items
3        order_payments
4         order_reviews
5                orders
6              products
7               sellers
8  category_translation

In [11]:
pd.read_sql(
    "SELECT * FROM orders LIMIT 5;",
    engine
)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [12]:
query = """
SELECT
    o.order_id,
    o.order_status,
    o.order_purchase_timestamp,
    c.customer_city,
    c.customer_state
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id
LIMIT 10;
"""

pd.read_sql(query, engine)

,order_id,order_status,order_purchase_timestamp,customer_city,customer_state
0,2711a938db643b3f0b62ee2c8a2784aa,delivered,2017-12-22 00:17:37,brasilia,DF
1,e481f51cbdc54678b7cc49136f2d6af7,delivered,2017-10-02 10:56:33,sao paulo,SP
2,53cdb2fc8bc7dce0b6741e2150273451,delivered,2018-07-24 20:41:37,barreiras,BA
3,47770eb9100c2d0c44946d9cf07ec65d,delivered,2018-08-08 08:38:49,vianopolis,GO
4,949d5b44dbf5de918fe9c16f97b45f8a,delivered,2017-11-18 19:28:06,sao goncalo do amarante,RN
5,ad21c59c0840e6cb83a9ceb5573f8159,delivered,2018-02-13 21:18:39,santo andre,SP
6,a4591c265e18cb1dcee52889e2d8acc3,delivered,2017-07-09 21:57:05,congonhinhas,PR
7,136cce7faa42fdb2cefd53fdc79a6098,invoiced,2017-04-11 12:22:08,santa rosa,RS
8,6514b8ad8028c9f2cc2374ded245783f,delivered,2017-05-16 13:10:30,nilopolis,RJ
9,76c6e866289321a7c93b82b54852dc33,delivered,2017-01-23 18:29:09,faxinalzinho,RS

In [19]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT order_id) AS unique_order_ids
FROM orders;
"""

pd.read_sql(query, engine)

   total_rows  unique_order_ids
0       99441             99441

In [14]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT customer_id) AS unique_customer_ids
FROM customers;
"""

pd.read_sql(query, engine)

   total_rows  unique_customer_ids
0       99441                99441

In [15]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT product_id) AS unique_product_ids
FROM products;
"""

pd.read_sql(query, engine)

   total_rows  unique_product_ids
0       32951               32951

In [ ]:
query = """
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT (order_id, order_item_id)) AS unique_rows
FROM order_items;
"""

pd.read_sql(query, engine)

   total_rows  unique_rows
0      112650       112650

In [22]:
from sqlalchemy import text

sql = """
ALTER TABLE customers
ADD PRIMARY KEY (customer_id);

ALTER TABLE orders
ADD PRIMARY KEY (order_id);

ALTER TABLE products
ADD PRIMARY KEY (product_id);

ALTER TABLE sellers
ADD PRIMARY KEY (seller_id);

ALTER TABLE order_items
ADD PRIMARY KEY (order_id, order_item_id);

ALTER TABLE order_payments
ADD PRIMARY KEY (order_id, payment_sequential);
"""

with engine.begin() as conn:
    conn.execute(text(sql))

In [23]:
statements = [
    """
    ALTER TABLE orders
    ADD CONSTRAINT fk_orders_customer
    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
    """,

    """
    ALTER TABLE order_items
    ADD CONSTRAINT fk_items_order
    FOREIGN KEY (order_id)
    REFERENCES orders(order_id)
    """,

    """
    ALTER TABLE order_items
    ADD CONSTRAINT fk_items_product
    FOREIGN KEY (product_id)
    REFERENCES products(product_id)
    """,

    """
    ALTER TABLE order_items
    ADD CONSTRAINT fk_items_seller
    FOREIGN KEY (seller_id)
    REFERENCES sellers(seller_id)
    """,

    """
    ALTER TABLE order_payments
    ADD CONSTRAINT fk_payments_order
    FOREIGN KEY (order_id)
    REFERENCES orders(order_id)
    """,

    """
    ALTER TABLE order_reviews
    ADD CONSTRAINT fk_reviews_order
    FOREIGN KEY (order_id)
    REFERENCES orders(order_id)
    """
]

with engine.begin() as conn:
    for statement in statements:
        conn.execute(text(statement))

In [24]:
pd.read_sql(
    """
    SELECT
        COUNT(*) AS rows,
        COUNT(DISTINCT review_id) AS unique_review_ids,
        COUNT(DISTINCT order_id) AS unique_order_ids
    FROM order_reviews;
    """,
    engine
)

    rows  unique_review_ids  unique_order_ids
0  99224              98410             98673

In [26]:
pd.read_sql(
    """
    SELECT
        table_name,
        constraint_name,
        constraint_type
    FROM information_schema.table_constraints
    WHERE table_schema = 'public'
      AND table_name = 'sellers';
    """,
    engine
)

  table_name        constraint_name constraint_type
0    sellers           sellers_pkey     PRIMARY KEY
1    sellers  2200_16424_1_not_null           CHECK

In [27]:
query = """
SELECT
    o.order_id,
    o.order_status,
    o.order_purchase_timestamp,
    c.customer_city,
    c.customer_state
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id
LIMIT 10;
"""

pd.read_sql(query, engine)

,order_id,order_status,order_purchase_timestamp,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,delivered,2017-10-02 10:56:33,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,delivered,2018-07-24 20:41:37,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,delivered,2018-08-08 08:38:49,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,delivered,2017-11-18 19:28:06,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,delivered,2018-02-13 21:18:39,santo andre,SP
5,a4591c265e18cb1dcee52889e2d8acc3,delivered,2017-07-09 21:57:05,congonhinhas,PR
6,136cce7faa42fdb2cefd53fdc79a6098,invoiced,2017-04-11 12:22:08,santa rosa,RS
7,6514b8ad8028c9f2cc2374ded245783f,delivered,2017-05-16 13:10:30,nilopolis,RJ
8,76c6e866289321a7c93b82b54852dc33,delivered,2017-01-23 18:29:09,faxinalzinho,RS
9,e69bfb5eb88e0ed6a785585b27e16dbf,delivered,2017-07-29 11:55:02,sorocaba,SP

In [28]:
query = """
SELECT
    o.order_id,
    o.order_status,
    oi.product_id,
    oi.seller_id,
    oi.price,
    oi.freight_value
FROM orders o
JOIN order_items oi
    ON o.order_id = oi.order_id
LIMIT 10;
"""

pd.read_sql(query, engine)

,order_id,order_status,product_id,seller_id,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,delivered,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,delivered,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,delivered,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,delivered,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,delivered,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,199.90,18.14
5,00048cc3ae777c65dbb7d2a0634bc1ea,delivered,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,21.90,12.69
6,00054e8431b9d7675808bcb819fb4a32,delivered,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,19.90,11.85
7,000576fe39319847cbb9d288c5617fa6,delivered,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,810.00,70.75
8,0005a1a1728c9d785b8e2b08b904576c,delivered,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,145.95,11.65
9,0005f50442cb953dcd1d21e1fb923495,delivered,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,53.99,11.40

In [29]:
pd.read_sql(
    """
    SELECT COUNT(*) AS number_of_orders
    FROM orders;
    """,
    engine
)

   number_of_orders
0             99441

In [30]:
pd.read_sql(
    """
    SELECT COUNT(*) AS rows_after_join
    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id;
    """,
    engine
)

   rows_after_join
0           112650

In [31]:
query = """
SELECT
    order_id,
    COUNT(*) AS number_of_items,
    SUM(price) AS total_item_price,
    SUM(freight_value) AS total_freight,
    AVG(price) AS average_item_price,
    COUNT(DISTINCT product_id) AS unique_products,
    COUNT(DISTINCT seller_id) AS number_of_sellers
FROM order_items
GROUP BY order_id
LIMIT 10;
"""

pd.read_sql(query, engine)

,order_id,number_of_items,total_item_price,total_freight,average_item_price,unique_products,number_of_sellers
0,00010242fe8c5a6d1ba2dd792cb16214,1,58.90,13.29,58.90,1,1
1,00018f77f2f0320c557190d7a144bdd3,1,239.90,19.93,239.90,1,1
2,000229ec398224ef6ca0657da4fc703e,1,199.00,17.87,199.00,1,1
3,00024acbcdf0a6daa1e931b038114c75,1,12.99,12.79,12.99,1,1
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,199.90,18.14,199.90,1,1
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,21.90,12.69,21.90,1,1
6,00054e8431b9d7675808bcb819fb4a32,1,19.90,11.85,19.90,1,1
7,000576fe39319847cbb9d288c5617fa6,1,810.00,70.75,810.00,1,1
8,0005a1a1728c9d785b8e2b08b904576c,1,145.95,11.65,145.95,1,1
9,0005f50442cb953dcd1d21e1fb923495,1,53.99,11.40,53.99,1,1

In [ ]:

# mutliple order_id could appers in different tables since one order could be repeated 3 or 4 times due to people could buy mutliple items in the same order 

#so we need to aggregate 

query = """
WITH item_features AS (
    SELECT
        order_id,
        COUNT(*) AS number_of_items,
        SUM(price) AS total_item_price,
        SUM(freight_value) AS total_freight,
        COUNT(DISTINCT product_id) AS unique_products,
        COUNT(DISTINCT seller_id) AS number_of_sellers
    FROM order_items
    GROUP BY order_id
)

SELECT
    o.order_id,
    o.order_status,
    o.order_purchase_timestamp,
    i.number_of_items,
    i.total_item_price,
    i.total_freight,
    i.unique_products,
    i.number_of_sellers
FROM orders o
LEFT JOIN item_features i
    ON o.order_id = i.order_id
LIMIT 10;
"""

pd.read_sql(query, engine)

,order_id,order_status,order_purchase_timestamp,number_of_items,total_item_price,total_freight,unique_products,number_of_sellers
0,00010242fe8c5a6d1ba2dd792cb16214,delivered,2017-09-13 08:59:02,1,58.90,13.29,1,1
1,00018f77f2f0320c557190d7a144bdd3,delivered,2017-04-26 10:53:06,1,239.90,19.93,1,1
2,000229ec398224ef6ca0657da4fc703e,delivered,2018-01-14 14:33:31,1,199.00,17.87,1,1
3,00024acbcdf0a6daa1e931b038114c75,delivered,2018-08-08 10:00:35,1,12.99,12.79,1,1
4,00042b26cf59d7ce69dfabb4e55b4fd9,delivered,2017-02-04 13:57:51,1,199.90,18.14,1,1
5,00048cc3ae777c65dbb7d2a0634bc1ea,delivered,2017-05-15 21:42:34,1,21.90,12.69,1,1
6,00054e8431b9d7675808bcb819fb4a32,delivered,2017-12-10 11:53:48,1,19.90,11.85,1,1
7,000576fe39319847cbb9d288c5617fa6,delivered,2018-07-04 12:08:27,1,810.00,70.75,1,1
8,0005a1a1728c9d785b8e2b08b904576c,delivered,2018-03-19 18:40:33,1,145.95,11.65,1,1
9,0005f50442cb953dcd1d21e1fb923495,delivered,2018-07-02 13:59:39,1,53.99,11.40,1,1